version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_instance
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - webnet

networks:
  webnet:
